//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::comment::Entity as Comment;
pub use super::comment::ActiveModel as CommentActiveModel;
pub use super::comment::Model as CommentModel;
pub use super::comment::Column as CommentColumn;