//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::post::Entity as Post;
pub use super::post::ActiveModel as PostActiveModel;
pub use super::post::Model as PostModel;
pub use super::post::Column as PostColumn;